import type { Metadata } from "next";
import localFont from "next/font/local";
import { Work_Sans } from "next/font/google";
import "./globals.scss";

const avenir = localFont({
  variable: "--font-avenir",

  src: [
    {
      path: "../data/font/AvenirNextLTPro-It.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../data/font/AvenirNextLTPro-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../data/font/AvenirNextLTPro-Bold.otf",
      weight: "700",
      style: "normal",
    },
  ],
});

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
  variable: "--font-work-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${avenir.variable} ${workSans.variable}`}>
        {children}
      </body>
    </html>
  );
}
